# Generated by Django 3.1.3 on 2021-07-29 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_order_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
